Testing cicd

diff --git a/.github/workflows/terra-acts.yml b/.github/workflows/terra-acts.yml
--- a/.github/workflows/terra-acts.yml
+++ b/.github/workflows/terra-acts.yml
@@ -112,30 +112,35 @@ jobs:
         run: cd terraform/net && terraform plan -no-color
         continue-on-error: true
 
-      - uses: actions/github-script@v4
-        if: github.event_name == 'pull_request' || github.event_name == 'push'
-        env:
-          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
-          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-        with:
-          script: |
-            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
-            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
-            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
-            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
-            <details><summary>Show Plan</summary>
-            \`\`\`\n
-            ${process.env.PLAN}
-            \`\`\`
-            </details>
-            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
-            github.issues.createComment({
-              issue_number: context.issue.number,
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              body: output
-            })
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
+
+
+
+#### TO DO, Fix the automatic comment creation upon PR or push ####
+
+#      - uses: actions/github-script@v5
+#        if: github.event_name == 'pull_request' || github.event_name == 'push'
+#        env:
+#          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
+#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+#        with:
+#          script: |
+#            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
+#            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
+#            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
+#            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
+#            <details><summary>Show Plan</summary>
+#            \`\`\`\n
+#            ${process.env.PLAN}
+#            \`\`\`
+#            </details>
+#            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
+#            github.rest.issues.createComment({
+#              issue_number: context.issue.number,
+#              owner: context.repo.owner,
+#              repo: context.repo.repo,
+#              body: output
+#            })
+#      - name: Terraform Plan Status
+#        if: steps.plan.outcome == 'failure'
+#        run: exit 1
